class JsonTagVariables():
    """ A static class which has all json value tag dering variables.
    """
    # config file parameters
    max_threads_count_process='MAX_THREADS_PROCESS'
    type_of_load_to_process='LOAD_TYPE'
    table_configuration_file_directory='CONFIG_FILE_DIR'
    log_base_directory = 'LOG_BASE_DIR'
    log_main_file_name_format ='LOG_MAIN_FILE_NAME_FORMAT'
    email_server_host='EMAIL_SMTP_SERVER_HOST'
    email_server_port='EMAIL_SMTP_SERVER_PORT'
    email_sender_emailid='EMAIL_SENDER_EMAIL_ID'
    email_receiver_list='EMAIL_RECEIVER_EMAIL_ID'
    email_subjectline='EMAIL_SUBJECT'
    wait_time_when_no_requestid_found='WAIT_MINUTES_NO_REQUEST'
    table_config_file_dir= 'TABLE_CONFIG_FILE_DIR'

    # Connection  Parameters File
    connectors = 'Database_Connectors'
    user_id = 'user_id'
    password = 'password'
    host = 'host'
    port = 'port'
    database = 'database'
    min_connection_pools = 'max_num_connections'
    max_connection_pools = 'max_num_connections'
    increment_connection = 'increment_connections'
    database_type = 'db_type'
    connection_pool = 'connection_pool'
    database_prod = 'database_product'
    enable_connection = 'enable_connection_pool_flg'

    # Log level config file details
    allpackages_log_level  = 'LOG_LEVEL'
    kafka_main_log_level='LOG_LEVEL--KAFKA_MAIN'
    thread_exec_log_level='LOG_LEVEL--THREAD_EXECUTION'
    db_initialiser_log_level='LOG_LEVEL--DB_INITIALISERS'
    json_value_extc_log_level='LOG_LEVEL--JSON_VALUE_EXTRACT'
    postgres_connection_pool_log_level='LOG_LEVEL--POSTGRES_CONNECTION_POOL'
    postgres_connector_log_level='LOG_LEVEL--POSTGRES_CONNECTOR'
    json_sql_value_extc_log_level='LOG_LEVEL--JSON_SQL_EXECUTION'
    kakfa_etl_log_level = 'LOG_LEVEL--KAKFA_ETL_CONFIG'
    kafka_connect_log_level = 'LOG_LEVEL--KAFKA_CONNECT_CONFIG'	 
       
    # kafka configuration tag variables :
    kafka_bootstrap_servers = 'KAFKA_BOOTSTRAP_SERVERS'
    default_consumer_group_id = 'DEFAULT_CONSUMER_GROUP_ID'
    session_timeout_inms = 'SESSION_TIMEOUT_INMS'
    default_offset_reset = 'DEFAULT_OFFSET_RESET'
    exclude_topics = 'EXCLUDE_TOPICS'
    processing_time_for_each_topic_inms = 'PROCESSING_TIME_FOR_EACH_TOPIC_INMS'
    consumer_consuming_timeout_inms = 'CONSUMER_CONSUMING_TIMEOUT_INMS'
    enable_auto_commit = 'ENABLE_AUTO_COMMIT'
    max_poll_interval_inms = 'MAX_POLL_INTERVAL_INMS'
    consumer_live_status_interval_ins ='CONSUMER_LIVE_STATUS_INTERVAL_INS'
    message_wait_exaust_interval_ins ='MESSAGE_WAIT_EXAUST_INTERVAL_INS'
    kafka_message_poll_wait_inms= 'KAFKA_MESSAGE_POLL_WAIT_INMS'
    kafka_insert_batch_number = 'KAFKA_INSERT_BATCH_NUMBER'
    group_id  = 'group.id'
    auto_offset_reset = 'auto.offset.reset'


    # SIL Tables config file details
    sil_table_root_tag='TABLE_GROUPS'
    list_of_tables_to_process='TABLES'
    load_type='LOAD_TYPE'
    table_categorisation='GROUP'
    max_thread_spin  = 'MAX_THREADS_SIL_PROCESS'

    # global json variables which has the path  to extract data from each table's associated config file
    target_db                         = 'TGT_CONNECTION'
    target_schema                     = 'TGT_SCHEMA_NAME'
    target_tbl                        = 'TGT_TABLE_NAME'
    delete_use_columns                = 'TABLE_UNIQUE_COLUMNS'
    pre_trig_other_sql                = 'PRE_TRIGGER_TASK--PRT_OTHER_TGT_SQL'
    pre_trig_trunc_ods_full           = 'PRE_TRIGGER_TASK--PRT_TRUNCATE_TGT_TABLE_FULL_SQL'
    pre_trig_trunc_ods_inc            = 'PRE_TRIGGER_TASK--PRT_TRUNCATE_TGT_TABLE_INC_SQL'
    dft_task                          = 'DATA_FLOW_TASK'
    dft_tgt_columns                   = 'DATA_FLOW_TASK--DFT_TGT_TABLE_COLUMNS'
    dft_tgt_column_dtype              = 'DATA_FLOW_TASK--DFT_TGT_COLUMNS_DTYPE'
    dft_insert_sql                    = 'DATA_FLOW_TASK--DFT_INSERT_SQL'
    del_process_tbls                  = 'DELETE_TASK--DELETE_SQL'
    post_trig_other_sql               = 'POST_TRIGGER_TASK--PST_OTHER_TGT_SQL'
